Repository hmcts/div-case-orchestration-service, pull requests merged in 2023-01, with the labels that each got.

#1726 DFR-1712 update suppressions
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-cos-pr-1726

#1732 Update Java Chart
  charts/div-cos/Chart.yaml
Labels: ns:divorce, prd:div, rel:div-cos-pr-1732

#1733 Update .terraform-version
  infrastructure/.terraform-version
  infrastructure/variables.tf
Labels: ns:divorce, prd:div, add-or-update, rel:div-cos-pr-1733

#1734 Update state.tf
  infrastructure/state.tf
Labels: ns:divorce, prd:div, no-changes, rel:div-cos-pr-1734
